# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

permissions: write-all

on:
  push:
    branches: [ main, test-e2e ]
  pull_request:
    branches: [ main, test-e2e ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Removing previous chrome instances on runner 
      run: sudo apt purge google-chrome-stable 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest coverage chromedriver-autoinstaller selenium pyvirtualdisplay
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install xvfb
      run: sudo apt-get install xvfb

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests and collect coverage
      run: |
        coverage run -m pytest

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

    - name: Generate report with lizard
      run: lizard > lizard-relatório.txt

    - name: Update resources
      uses: test-room-7/action-update-file@v1
      with:
          file-path: lizard-relatório.txt
          commit-msg: Auto generated lizard report
          github-token: ${{ secrets.GITHUB_TOKEN }}    

